### ISSUE TITLE
AkSwitch Doesn't Work on Quest

### ISSUE THREAD

**Issue by Gab4Chan** [AoiKamishiro/VRChatPrefabs#1]
It works on other VR other than Quest
is there a way to fix it?

**Comment by AoiKamishiro** [comment]
Does this happen when you use Oculus Quest2?
And which is it, when used by itself or connected to a PC?

**Comment by Gab4Chan** [comment]
there is not button outline and it cannot be used but it works on other vr like Rift S
and it's both connected and used by itself does not work

**Comment by AoiKamishiro** [comment]
AKSwitches must be touched by the VR user with their own hands, unless "Disable Physical Interaction" is checked.
In that case, the button will not have an outline for Interact.

Also, for the first 5 seconds after entering the world, you will be able to Interact due to a bug in VRChat.
