### ISSUE TITLE
[EventCalendar] イベント名の絵文字対応

### ISSUE THREAD

**Issue by esperecyan** [AoiKamishiro/VRChatPrefabs#2]
カレンダー画像生成側の話ですが、イベント名に含まれる絵文字に対応することはできませんでしょうか。

**Comment by AoiKamishiro** [comment]
返信が遅くなりすみません。
現在、見やすさの観点などから NotoSansJP-Regular のみを使用しています。
以前も絵文字に対応できるフォントを探していたのですが、当方フォントに関する知識が浅いため、今一ピンとくるものが見つからず、保留としておりました。
もし、絵文字に対応したフォントをご存じであれば、ぜひともそれを試してみたく思います。

**Comment by esperecyan** [comment]
返信有り難うございます。
Notoであれば、Noto Emojiはいかがでしょうか？
https://github.com/googlefonts/noto-emoji

**Comment by AoiKamishiro** [comment]
Noto-Emojiで試してみたのですが、Noto-Emojiに含まれるAscii文字などが元のNoto-Sansとは大幅に異なるデザインでした。
そのため、Noto-Sansに含まれない文字かどうかを判定し、含まれない場合であればNoto-Emojiを使用するように生成側に手を加えてる処理を実装しようと試みたのですが、現行の使用しているシステム(.net 3.1)ではその機能を実装できず、移行先のシステム(.net 6)では、描画に問題が発生してしまいました。
そのため、この変更は次回の大規模更新（イベント詳細の表示機能などを追加予定）の際に、抜本的に生成システムを変更して実装しようと思います。

**Comment by AoiKamishiro** [comment]
現行の仕様のまま絵文字への対応が完了しました。

**Comment by esperecyan** [comment]
確認しました！　対応有り難うございます！
